name: qa_integration_project
description: Dart-based QA automation framework
version: 1.0.0

environment:
  sdk: '^3.7.0'

dependencies:
  http: ^1.3.0
  # other dependencies...
  dio: ^5.0.0 # For advanced API testing
  test: ^1.16.0 # Unit testing framework
  json_serializable: ^6.0.0
  mockito: ^5.0.0 # Mocking library for Dart
  
