name: Test Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:  # This allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a script
        run: echo "Hello, World!"
